DROP DATABASE IF EXISTS VOCABS_DB;

CREATE DATABASE VOCABS_DB;

USE VOCABS_DB;

CREATE TABLE VOCABS(
	ID INTEGER(10) AUTO_INCREMENT NOT NULL,
    WORD VARCHAR(100) NOT NULL,
    MASTERED BOOLEAN,
    PRIMARY KEY(ID)
);